### ISSUE TITLE
Regarding mode of submission and publication of the report

### ISSUE THREAD

**Issue by AvirupJU** [ICVGIP-Challenge/NetworkQuantization-21#1]
What is the mode of submission for this contest? Do we need to submit the Github repository or just a report would suffice?
Also, will the the report be published at the said conference?

**Comment by pksvision** [comment]
As instructed in the README, each participating team is required to upload only the generated **output.txt** file during the validation phase. For testing phase, separate set of instructions will be given. Participants are suggested to keep a watch on this repo. for further details. 

Reg. the **report**, nothing conclusive has been decided as of now.
