### ISSUE TITLE
About wildlife detection

### ISSUE THREAD

**Issue by iscyy** [ICVGIP-Challenge/NetworkQuantization-21#3]
Is anyone responsible for answering questions in this competition? Thank you. There is an issue.
https://github.com/ICVGIP-Challenge/SpeciesDetection-21

**Comment by pksvision** [comment]
Hi @Him-wen this repository for different task. Pl post your query over [here](https://github.com/ICVGIP-Challenge/SpeciesDetection-21/issues) .
